### ISSUE TITLE
Explain lack of windows support in README

### ISSUE THREAD

**Issue by CohenArthur** [Skallwar/suckit#114]

**Comment by hbina** [comment]
Its already there?

**Comment by CohenArthur** [comment]
> Its already there?

We wrote that it's not available but didn't go into detail as to why, which is the reason for this issue

**Comment by mr-bo-jangles** [comment]
This should be resolved with https://github.com/Skallwar/suckit/pull/134. It changes nothing for Unix hosts, but handles the windows case for you.

**Comment by Skallwar** [comment]
Fixed by #134
