### ISSUE TITLE
The following labels could not be found: `domain: deps`.

### ISSUE THREAD

**Issue by CohenArthur** [Skallwar/suckit#129]
The following labels could not be found: `domain: deps`.

_Originally posted by @dependabot[bot] in https://github.com/Skallwar/suckit/issues/125#issuecomment-872779463_

This seems to be due to an "issue" (maybe not?) with `dependabot.yml`

**Comment by pinkforest** [comment]
It's just a warning, dependabot uses labels to tag it's PRs.

You may want to add those labels as they are generated via automation and can be used to trigger things later.

You can create them in pull requests / labels:

https://github.com/Skallwar/suckit/labels

**Comment by CohenArthur** [comment]
Aaaaah, fantastic thanks a lot. That makes sense!
