### ISSUE TITLE
Minimum Supported Rust Version (MSRV)

### ISSUE THREAD

**Issue by pinkforest** [Skallwar/suckit#130]
Rust has RFC open for MSRV:
https://github.com/rust-lang/rust/issues/65262

Cargo has added it:
https://github.com/rust-lang/cargo/pull/8037

I test MSRV as part of my CI:
https://github.com/pinkforest/gis_puller/blob/main/.github/workflows/CI.yml

I have multiple toolchains so I just usually run & test with +toolchain to figure this out.

Badge is available from shields.io - e.g. 1.47.0:
`![MSRV](https://img.shields.io/badge/MSRV-1.47.0-blue)`

- [x] Determine MSRV
- [ ] Specify in manifest
- [ ] Add to CI to test MSRV in matrix
- [ ] Add badge

**Comment by Skallwar** [comment]
I'm running [foresterre/cargo-msrv](https://github.com/foresterre/cargo-msrv). I will report the results tomorrow

**Comment by Skallwar** [comment]
The MSRV is: 1.44.1

**Comment by pinkforest** [comment]
Cool!

I would additionally eventually recommend setting in README/documentation:

 - Policy promise for stable minus 2 for current development/main branch
 - Tag in a table respective MSRV with each release/crate tag

Not too bothered usually but for heavily used libraries it might make sense eventually (hello enterprise world)
