### ISSUE TITLE
Request - Limit download to subdirectory

### ISSUE THREAD

**Issue by mr-bo-jangles** [Skallwar/suckit#135]

**Comment by pinkforest** [comment]
@mr-bo-jangles you could already do this with -i | --include regex filter?

It does suck the index pages tho.

$ suckit -v -j 1 --delay 1 -i "https://github.com/Skallwar/suckit/issues/\d+$" https://github.com/Skallwar/suckit/issues/135
2021-07-07 09:05:15.923696530 +10:00: [INFO] Visited: https://github.com/Skallwar/suckit/issues/135
2021-07-07 09:05:17.092501186 +10:00: [INFO] Visited: https://github.com/opensearch.xml
2021-07-07 09:05:19.043517442 +10:00: [INFO] Visited: https://github.com/fluidicon.png
2021-07-07 09:05:20.112460134 +10:00: [INFO] Visited: https://github.com/manifest.json
2021-07-07 09:05:21.543640029 +10:00: [INFO] Visited: https://github.com/
2021-07-07 09:05:23.159025034 +10:00: [INFO] Visited: https://github.com/signup?ref_cta=Sign+up&ref_loc=header+logged+out&ref_page=%2F%3Cuser-name%3E%2F%3Crepo-name%3E%2Fissues%2Fshow&source=header-repo
2021-07-07 09:05:24.410392198 +10:00: [INFO] Visited: https://github.com/features
^C

$ ls -laR
.:
total 12
drwxrwxr-x  3 foobar foobar 4096 Jul  7 09:05 .
drwxr-xr-x 65 foobar foobar 4096 Jul  7 09:04 ..
drwxrwxr-x  3 foobar foobar 4096 Jul  7 09:05 github.com

./github.com:
total 12
drwxrwxr-x 3 foobar foobar 4096 Jul  7 09:05 .
drwxrwxr-x 3 foobar foobar 4096 Jul  7 09:05 ..
drwxrwxr-x 3 foobar foobar 4096 Jul  7 09:05 Skallwar

./github.com/Skallwar:
total 12
drwxrwxr-x 3 foobar foobar 4096 Jul  7 09:05 .
drwxrwxr-x 3 foobar foobar 4096 Jul  7 09:05 ..
drwxrwxr-x 3 foobar foobar 4096 Jul  7 09:05 suckit

./github.com/Skallwar/suckit:
total 12
drwxrwxr-x 3 foobar foobar 4096 Jul  7 09:05 .
drwxrwxr-x 3 foobar foobar 4096 Jul  7 09:05 ..
drwxrwxr-x 3 foobar foobar 4096 Jul  7 09:05 issues

./github.com/Skallwar/suckit/issues:
total 12
drwxrwxr-x 3 foobar foobar 4096 Jul  7 09:05 .
drwxrwxr-x 3 foobar foobar 4096 Jul  7 09:05 ..
drwxrwxr-x 2 foobar foobar 4096 Jul  7 09:05 135

./github.com/Skallwar/suckit/issues/135:
total 120
drwxrwxr-x 2 foobar foobar   4096 Jul  7 09:05 .
drwxrwxr-x 3 foobar foobar   4096 Jul  7 09:05 ..
-rw-rw-r-- 1 foobar foobar 112886 Jul  7 09:05 index_no_slash.html

If this doesn't cover it, would you have any example to refer to?

**Comment by mr-bo-jangles** [comment]
Ok, it looks like the include functionality is much more robust than I thought it was. 

Out of interest, does that regex support Unicode characters (Cyrillic, Chinese, etc?). 

How would I be able to say for example: Scrape this "https://site.to.scrape/public/" and ensure that the scraped directories under it consists of all alphanumeric+space regardless of language?

**Comment by pinkforest** [comment]
Should be, it's not tested much though as far as I can see :)

As Rust String type is UTF-8 around, 

I would expect it's input is relayed to Regex as such from clap opt struct that comes from ~directly from CLI args.

Now localising regex ranges is a bit different for groups can be tricky.

Python provides string.letters that honors locale and can be used as exact list of allowed characters per locale.

Not sure if Rust has any.

Rust Regex library has UTF-8 support described here:
https://docs.rs/regex/1.5.4/regex/

There are several other ways to do it in Regex but need to know more about your need / what it is supposed to accomplish.

In some cases it might be best to use the exclude pattern within regex.

But when it comes to UTF-8 there are a lot of edge cases :fire:

**Comment by pinkforest** [comment]
@mr-bo-jangles want to close this issue and open new issue about clarifying UTF-8 / URL Encoding handling for --include ?

It would be helpful to have some concrete minimal reproducible examples that we can add to tests.

**Comment by CohenArthur** [comment]
We are using [Rust's regex crate](https://crates.io/crates/regex) and I believe that it would be be best to keep it. [It can handle Unicode](https://docs.rs/regex/1.5.4/regex/#unicode) so I think your use-case should be covered @mr-bo-jangles but I'm not certain of course. Feel free to test it and report back!
