### ISSUE TITLE
Scroller SVG Image optimisation

### ISSUE THREAD

**Issue by pinkforest** [Skallwar/suckit#136]
I see someone else hit #119 before

**Network Perspective**

asciicinema.org sets max age 0s so it is never pulled from cache but always pulls it remotely via Github's proxy.

But network/transfer of the file doesn't cause this freezing.

**Rendering Issue**

CPU gets a bit antsy from processing this 256 KB svg:
`[![asciicast](https://asciinema.org/a/327889.svg)](https://asciinema.org/a/327889)`

Considering [these SVGs](https://github.com/miraclx/svgembed) don't do this, 

Content of the svg is what causes the unresponsiveness (CPU busy) and not the size of it.

This SVG is animating (via ad-hoc render) quite large canvas size:
`<svg .. width="1357.766666613" height="1391.6">`

I can't just reduce the canvas as the whole animation is fixed to that canvas size so it has to be re-recorded for size.

Just like WYSIWYG HTML editors were quite bloaty back in the time now we have XML CSS and everything else to deal with :)

SVG can be it's own [can of worms](https://www.fortinet.com/blog/threat-research/scalable-vector-graphics-attack-surface-anatomy).

Processing latency is not visible at asciicinema.org as it displays there the application/x-asciicast but when embedding the .svg Mozilla gets a bit busy.

I'll record a smaller version with less animated rows (thus smaller canvas size) aiming for 10% or less size and we can host it cached via some CDN e.g. jsDelivr off Github too.

I am additionally browsing behind choppy LTE and in total sometimes I get 21 seconds delay before I can click any tabs/other buttons if I ended up navigating via repo main page that shows the README.md embedding the svg :sob: 

(Adjusting the size of the svg image here doesn't work as it crops after loading and doesn't scale either and if it would do that it would be after the processing plus even additional processing that scales it down)
(Same thing as with thumbnails, one has to reduce the imagesize when you have a lot of images in one page, on-the-fly scaling down doesn't provide the optimisation as scale down is after loading the huge images)

**Comment by pinkforest** [comment]
Using [termtosvg](https://github.com/nbedos/termtosvg) 

**Recording**

```
record suckit-record.txt -g 82x12
suckit -v -j 2 -o ./ http://books.toscrape.com  (2 seconds then C-d)
ls -laR books.toscape.com (and quick C-c)
```

I get 666 Lines in moderate standard GCP instance :dagger: 

**Render**

Then I bluntly "render: it out from the .txt I just recorded with 5s delay loop.

```
$ termtosvg render suckit-record.txt suckit.svg -D 5000
Rendering started
Rendering ended, SVG animation is suckit.svg
$ du -h suckit.svg 
156K	suckit.svg
$ 

```
Result is that it loads instantly no CPU going crazy or freezing around.

Neither I need to click play e.g. no controls required.

I will further optimize that .txt

**Comment by pinkforest** [comment]
First I will adjust the timing that types the initial prompt command:

```txt
[0.0, "o", "$ "]
[0.754998, "o", "suckit -v -j 2 -o ./ http://books.toscrape.com"]
[1.07086, "o", "\r\n"]
```
There is a second delay from blunt copy-paste of the command... it's pretty blunt :/

But if we want to show it like it's typed, we have to key it like this with 60ms delay each character:
```txt
{"version": 2, "width": 82, "height": 1}
[0.0, "o", "$ "]
[0.060, "o", "s"]
[0.120, "o", "u"]
[0.180, "o", "c"]
[0.240, "o", "k"]
[0.300, "o", "i"]
[0.360, "o", "t"]
[0.420, "o", " "]
[0.480, "o", "-"]
[0.540, "o", "v"]
[0.600, "o", " "]
[0.660, "o", "-"]
[0.320, "o", "j"]
[0.380, "o", " "]
[0.440, "o", "2"]
[0.500, "o", " "]
[0.560, "o", "-"]
[0.620, "o", "o"]
[0.700, "o", " "]
[0.760, "o", "."]
[0.820, "o", "/"]
[0.880, "o", " "]
[0.940, "o", "h"]
[1.0, "o", "t"]
[1.060, "o", "t"]
[1.120, "o", "p"]
[1.180, "o", ":"]
[1.240, "o", "/"]
[1.300, "o", "/"]
[1.360, "o", "b"]
[1.420, "o", "o"]
[1.480, "o", "o"]
[1.540, "o", "k"]
[1.600, "o", "s"]
[1.660, "o", "."]
[1.720, "o", "t"]
[1.780, "o", "o"]
[1.840, "o", "s"]
[1.900, "o", "c"]
[1.960, "o", "r"]
[2.020, "o", "a"]
[2.080, "o", "p"]
[2.140, "o", "e"]
[2.200, "o", "."]
[2.260, "o", "c"]
[2.320, "o", "o"]
[2.380, "o", "m"]
[3.0, "o", "\r\n"]
```

We can incorporate nice rolling prompt to our svg demo:
https://cdn.jsdelivr.net/gh/pinkforest/svg-testing-bloat/prompt-natural.svg

**Comment by CohenArthur** [comment]
Wow, thanks for putting the time in this, that's really appreciated!

Regarding the typing/rolling effect, it feels like this is easily scriptable so we might look into it. The output is very nice

I haven't had the time to look into it, but isn't there anything we can do while using asciinema? You seem knowledgeable about SVGs haha

**Comment by pinkforest** [comment]
Check this out:
https://github.com/pinkforest/svg-testing-bloat

**Comment by CohenArthur** [comment]
> Check this out:
> https://github.com/pinkforest/svg-testing-bloat

Wow, that's really cool!

The only thing that I just remembered is that we also added the asciinema to show the speed of the scraper. So I think the Blunt Timings would be better at showcasing speed

**Comment by pinkforest** [comment]
> The only thing that I just remembered is that we also added the asciinema to show the speed of the scraper. So I think the Blunt Timings would be better at showcasing speed

Problem with that is that it doesn't illustrate the usage very well... 

And blunt timings are very variable and doesn't really show what is going on well.

Rather have fixed timings so it is repeatable and not reliant on things like internet speed/hardware etc.

I could look into leaving the prompt on line 1 e.g. ansi \e[1;1h and then input everything from \e[2;1h if I remember how ANSI worked for coordinates.

**Comment by pinkforest** [comment]
Aand if we want to be meaningfully interactive 

Then the progress bar and such things are must 

More ANSI-graphical things on CLI world like trafshow and others are more usable for that.

Lots of rolling text doesn't really make much sense

When it could be presented instead in CLI ANSI graphical form just like a lot of the examples in ascii cinema already show.

**Comment by Skallwar** [comment]
I wonder if using a gif will be better looking. We avoid the performance issue + the video is playing automagically

**Comment by pinkforest** [comment]
No.

I fixed the performance issue already that freezes firefoxes within Svg for which I pushed a PR.

GIF is binary image data (think pixels) and it doesn't know how to animate and it will be gigantic at these sizes.

SVG when used appropriately is very performant.

**Comment by Skallwar** [comment]
> My SVG also plays automatically.

For some reason, it did not on my phone? But it works on my phone.

**Comment by pinkforest** [comment]
> For some reason, it did not on my phone? But it works on my phone.

Are you using some esoteric android browser you compiled from source by yourself perhaps? :laughing: 

For me works on:
 - iPad on Brave
 - iPad on Safari
 - Linux on Mozilla
 - iOS iPhone 12 Pro Max on Safari

**Comment by pinkforest** [comment]
Anyways fixed @ #139

Thanks for the patience everyone :rabbit: :smile:

**Comment by CohenArthur** [comment]
> Are you using some esoteric android browser you compiled from source by yourself perhaps? laughing
Knowing him, probably :eyes:

**Comment by Skallwar** [comment]
Thanks for your work 😊
