### ISSUE TITLE
Resume download for large websites

### ISSUE THREAD

**Issue by harrystuart** [Skallwar/suckit#218]
What is the best way to resume a download of a large website? I see there is a future feature planned to tackle this, but what is the current solution? Thanks.

**Comment by Skallwar** [comment]
There is no current "solution". One hacky way is to set `--retries` with a high enough value like `5` and just send the job to the background usually `CTRL+Z`. You can then resume with `fg`.
The downside is that you can't reboot

**Comment by harrystuart** [comment]
Yeah, my concern is if my internet drops out. I suspect the download will take about a 3 days. The ability to resume download would be great - I look forward to that release. Cheers
