### ISSUE TITLE
Sites with foreigner characters are shown as gibberish.

### ISSUE THREAD

**Issue by xGigaa** [Skallwar/suckit#63]
Some sites are shown with gibberish characters instead of the correct once, however this doesn't seems to happen consistently.

![Screenshot_20200505_185303](https://user-images.githubusercontent.com/24317395/81094154-66c3c000-8f03-11ea-8dd4-d855b2976f62.png)

NRK.no shows the correct characters (æøå) but gamlegjerpen.no does not.
Seems like gamlegjerpen.no does not contain: `<meta charset="utf-8">`
Not sure if that's why it gets displayed as gibberish on the downloaded copy but it's something.

**Comment by CohenArthur** [comment]
@xGigaa thanks a lot for reporting an issue. Can you paste the exact command you typed ?

**Comment by xGigaa** [comment]
Sure.
`./suckit http://www.gamlegjerpen.no/ -j 8 -o /run/media/gigaa/67489829-d767-48c7-aabd-f7c3180f5895/backup/gamlegjerpen`
And
`./suckit https://www.nrk.no/ -j 8 -o /run/media/gigaa/67489829-d767-48c7-aabd-f7c3180f5895/backup/nrk`
(NRK is a large news site so be wary if you try to download the whole site)

**Comment by edo0** [comment]
The same happens with very basic accented Spanish characters.
e.g.  `suckit http://www.spagnolo-online.de/` (2 GB website)

**Comment by Skallwar** [comment]
My first approach was to use the the charset="XXX" in http headers fields. But some site does not provide it. So my next bet is to use a regex in the header of the page to fetch charset="XXXX". Is this a good idea ?

**Comment by Skallwar** [comment]
I got this working bassed on the regex thing. The code is ugly but it's getting there. #105
