### ISSUE TITLE
Feature: Unlimited download

### ISSUE THREAD

**Issue by Skallwar** [Skallwar/suckit#64]
-d 'big number here' is not clean way to download a whole website

**Comment by SpyrosRoum** [comment]
Can I take a look at this too? I am thinking if you put -1 it will download everything by checking if `args.depth == -1 || depth < args.depth` [here](https://github.com/Skallwar/suckit/blob/master/src/scraper.rs#L102)

**Comment by CohenArthur** [comment]
Definitely ! I like -1 as value for unlimited and default value
