### ISSUE TITLE
Panic with EmptyHost

### ISSUE THREAD

**Issue by johanstokking** [Skallwar/suckit#69]
I'm getting the following panics;

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: EmptyHost', src/scraper.rs:97:37
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/scraper.rs:150:9
```

Could be a link without host?

**Comment by CohenArthur** [comment]
Could you please paste the command you used ? Thanks for reporting it !

**Comment by johanstokking** [comment]
Sure; I'm downloading our website; 

```
$ suckit https://www.thethingsnetwork.org -j 8 -o ./thethingsnetwork.org -v
```

It seems to fail roughly at the same time, but it's hard to tell as lots of content gets downloaded correctly before this panic.
