### ISSUE TITLE
Feature: Disable SSL checks

### ISSUE THREAD

**Issue by Skallwar** [Skallwar/suckit#71]
We need to be able to scrap websites with an invalid certificate

**Comment by loo-kaa** [comment]
It seems to me that by adding the parameter `--disable-certs-checks` the download works for most cases: i've tested using [https://badssl.com/](https://badssl.com/). What "invalid certificate means for you ? Is this an old issue, maybe it can be closed. I'm a newbie but i'm trying to get into open source maintaining.

**Comment by Skallwar** [comment]
Good catch! This is indeed an old issue and it was fixed by #203.
I did not know about https://badssl.com/. If you want to try to add a test, I will gladly help/review. Note that Suckit is participating to [hacktoberfest](https://hacktoberfest.com/)

**Comment by loo-kaa** [comment]
I'll try to add a test, thanks for now👍
