### ISSUE TITLE
Feature: Limit downloading to certain file extensions with pattern

### ISSUE THREAD

**Issue by CohenArthur** [Skallwar/suckit#75]
A nice option would be to restrict the downloading (but not the visiting) of content with a certain extension. For example, running `suckit <url> --extensions "mp[3-4]"` would only download MP3 and MP4 files using a regex

**Comment by creativcoder** [comment]
Hey @CohenArthur I'd like to work on this!

**Comment by CohenArthur** [comment]
Sure ! Thanks a lot @creativcoder

**Comment by CohenArthur** [comment]
@creativcoder I think it would be nice to also add a form of "exclusion" to exclude some file types, using a regex as well. We can open a separate issue or you can work on it as well if you want

**Comment by creativcoder** [comment]
Exclude as in not visit the links? Sure, will add that as well!

**Comment by CohenArthur** [comment]
As in visit the links to find more links, but do not download the files
