### ISSUE TITLE
Disk: Stop flat archive creation

### ISSUE THREAD

**Issue by Dedsec1** [Skallwar/suckit#77]
hi :)

loving this program so far but just had one feature idea / request, is it possible to have an like a -mirror flag or sitemap output flag so the downloader can output with the same folder structure as the site based on url or folders that its downloading.  the reason i ask is when trying this on a few public open directories it makes several folders with the site name and then with the file name and creates folders for each file / page. 

here is an example

https://releases.ubuntu.com/19.10/
https://releases.ubuntu.com/20.04/

so we could setup suckit to output to releases.ubuntu.com/19.10/, releases.ubuntu.com/20.04 and  etc 

Thanks

**Comment by Skallwar** [comment]
Thanks for giving it a spin :)

This should be the default behavior. We will work on that

**Comment by Dedsec1** [comment]
no problem,  i never used a rust based program before and its pretty quick so far.
