### ISSUE TITLE
Save files with extension

### ISSUE THREAD

**Issue by tbillington** [Skallwar/suckit#79]
Awesome project :) 

Haven't seen anyone else mention it so I might be using it wrong.. but I am getting all downloaded files without an extension. Here is a screenshot from downloading a small site.

My assumption would be it would save files `about.html`, `favicon.png`, `global.css` etc. It looks like they're mostly there but with an underscore instead of a period.

On mac (10.15.4) if that helps, installed from `cargo --git` `Installed package suckit v0.1.0 (https://github.com/skallwar/suckit#16a5ed9c) (executable suckit)`

![Screen Shot 2020-05-07 at 9 54 32 am](https://user-images.githubusercontent.com/2771466/81239703-ead39000-9048-11ea-95b6-72985dafbb36.png)

**Comment by Taubin** [comment]
Same happens with it installed through cargo on WSL.

**Comment by CohenArthur** [comment]
This is *intended* but it's not something we have to keep. I agree it's a bit weird. When you open one of the pages with a browser, it will get all pages correctly.

We'll definitely change that! It shouldn't change anything right now, but maybe image viewers and such are not happy about it.

Thanks for the report !

**Comment by Skallwar** [comment]
This is hard to do without #77 I'm working on a solution that will solve both of this issue

**Comment by turkeyphant** [comment]
> My assumption would be it would save files `about.html`, `favicon.png`, `global.css` etc. It looks like they're mostly there but with an underscore instead of a period.

Same here except it also replaces ```/``` with an ```_``` meaning the directory structure is lost as well as the file extensions.

**Comment by Skallwar** [comment]
> Same here except it also replaces `/` with an `_` meaning the directory structure is lost as well as the file extensions.

Should be fixed by #77. I can't work on this at the moment

**Comment by Skallwar** [comment]
This should be good now. @tbillington can you confirm that the current version of SuckIT does what you want ?

**Comment by Skallwar** [comment]
Feel free to reopen this if needed
