### ISSUE TITLE
Asciinema recording in the readme is archived

### ISSUE THREAD

**Issue by dvtkrlbs** [Skallwar/suckit#81]
<img width="938" alt="Screen Shot 2020-05-08 at 18 31 06" src="https://user-images.githubusercontent.com/24792168/81421573-535e6200-915a-11ea-8a81-df7ea01e0ad5.png">

**Comment by CohenArthur** [comment]
Thanks @dvtkrlbs , this is fixed in #80 but it hasn't been merged yet :)
