### ISSUE TITLE
After scraping https://getbootstrap.com , having problem rendering

### ISSUE THREAD

**Issue by guruprasaad123** [Skallwar/suckit#86]
# my first Experiment :

I tasked **suckit** to scrape the website - https://getbootstrap.com so that i can have bootstrap documentations offline it seems to have downloaded the website but i opened the website in my browser it isn't rendering properly ( having issues with css files i guess )

And this Added feature to **suckit**

**Comment by CohenArthur** [comment]
Hi, thanks a lot for your issue ! I think this is a duplicate of #70 . We've had a report for it already

**Comment by guruprasaad123** [comment]
> Hi, thanks a lot for your issue ! I think this is a duplicate of #70 . We've had a report for it already

Sorry please dont mind
