### ISSUE TITLE
What type of regex works?

### ISSUE THREAD

**Issue by nmjohnson** [Skallwar/suckit#91]
What are the wildcards for include/exclude regex? I tried %, *, and . and I don't think any of them worked. The script eventually runs into some errors and saves nothing. I want to find a specific .aspx filename and only save those because this website probably has at least 10 billion unique pages.

**Comment by CohenArthur** [comment]
@nmjohnson the Regexes are the one from the standard [Rust Regex crate](https://github.com/rust-lang/regex). The syntax is the same as Perl regexes.

So to download all aspx pages, you should use the following regex `.*.aspx`
