### ISSUE TITLE
Remove fragment hash from scraped URLs

### ISSUE THREAD

**Issue by pjsier** [Skallwar/suckit#99]
Scraping a web page with multiple links to specific sections on another page (i.e. "/#section") results in duplicate downloads of the same page because the URL fragment is different. According to the [`fragment` method docs](https://docs.rs/url/2.1.1/url/struct.Url.html#method.fragment) this portion of the URL isn't typically sent to the server, and in my understanding it would only make a difference in client-side updates that wouldn't be tracked here anyway.

Should the URL fragment be removed from the URL to avoid duplicates? If so I can put in a PR for that

**Comment by CohenArthur** [comment]
Sure, that's a good catch. Feel free to open a PR :+1:
